name: pre-commit

on:
  pull_request:
  push:
    branches: [master, newsviz:stage]

jobs:
  pre-commit:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set python
        uses: actions/setup-python@v2.1.3

      - name: pre-commit-action
        uses: pre-commit/action@v2.0.0

